Support testing from cfgov-refresh
Now supports automatic testing from cfgov-refresh using `python
manage.py test regcore` to test satellite apps.

The tests for this repo have broken, due to what looks like a change to
haystack. Error is `ImportError: cannot import name connection_router`
due to `from haystack import connection_router, connections`.

We’re moving to regs 2.0 in the near future and the tests all pass from
cfgov-refresh, so I’m making a PR even though some tests don’t run
properly.